### ISSUE TITLE
Something About The Proxy

### ISSUE THREAD

**Issue by CrazyComputer2008** [ExplodingBottle/JMagicProxy#1]
Hello! I'm using your proxy and set all the things up both on my client and server(Windows Server 2008 R2).Now I can use the proxy system-wide.but I can't access [https://www.update.microsoft.com/v11/3/legacy/windowsupdate/selfupdate/wuident.cab](url) to download wuident.cab.

**Comment by CrazyComputer2008** [comment]
I forgot to turn off java's safty config. After turning it off,everyting works fine.
PS:In my case,I had to access [https://www.microsoft.com](url) to install the CA from the site manually.

**Comment by ExplodingBottle** [comment]
I have reopened the issue because I would like to know if you had to install the CA manually on the client or on the server.
Thanks by advance for answering.

**Comment by CrazyComputer2008** [comment]
In my case the generated certificate installer and the independent certificate(updroot.cer) can't build trust on my computer. It semms like the installed certificate is different from the server. So I access the update website in https,then IE will ask you not to access the site because the CA wasn't trusted. I skipped the warning,and installed the certificate which provided by the server.
![image](https://github.com/ExplodingBottle/JMagicProxy/assets/49907719/8dd5f914-e90e-4fbc-815e-a31a32cd2034)
![image](https://github.com/ExplodingBottle/JMagicProxy/assets/49907719/5d749588-d0d9-41b8-897a-b49e8c570c6a)

**Comment by CrazyComputer2008** [comment]
By the way I also wanted to add a feature.Another people in the MSFN posted an feature to scan more updates than usual.(such as WGA Tool and End-of-support message).
Here is some settings in his proxy:
```
In the other proxy you have to create the following redirects:
> https://www.update.microsoft.com/v6/ClientWebService/client.asmx 
> https://fe2.update.microsoft.com/v6/ClientWebService/client.asmx

> https://www.update.microsoft.com/v6/UpdateRegulation/updateregulation.asmx
> https://fe2.update.microsoft.com/v6/UpdateRegulationService/updateregulation.asmx

> https://fe2.update.microsoft.com/v11/3/legacy/windowsupdate/selfupdate/wuident.cab 
> https://web.archive.org/web/20070110011725/update.microsoft.com/v6/windowsupdate/selfupdate/wuident.cab  (this only for GET requests)

Then modify response headers for any address containing /wuident.cab:
ADD Content-Length: "7427"
ADD Last-Modified: "Fri, 20 Oct 2006 02:00:03 GMT"
```
I think the only thing we are missing is modify wuident.cab.
Hope you can think about it! Thank you again for your wonderful work!

**Comment by CrazyComputer2008** [comment]
I think the wuident.cab can be also download as a local file due to network issue in my country,instead of being download directly from the web.archive.org.

**Comment by ExplodingBottle** [comment]
Hello !
This proxy already redirects www.update.microsoft.com requests to fe2.update.microsoft.com, both in HTTP and HTTPS, which means that the exact same behavior as the old Windows Update is here. This proxy is not a WSUS proxy, it is literally a gateway to talk to the new Windows Update server with an old system, which makes that you will get the WGA tool as well as the end of support notification update. If you check on the Wiki page, at some point you can see that it is installing the Windows Genuine Advantage Notification Tool.
For the certificate on the client, updroot.cer, you must install it as seen in the step 3 of the Wiki (https://github.com/ExplodingBottle/JMagicProxy/wiki/WUProxy-Windows-XP)

And for the wuident.cab file, it is already redirected.

If you understand Java, you can check the code of WUProxy (the part which only handles Windows Update stuff)
https://github.com/ExplodingBottle/JMagicProxy/blob/master/src/io/github/explodingbottle/jmagicproxy/implementation/WUProxy.java

**Comment by CrazyComputer2008** [comment]
Actually the result of my process are the same,but the source files are came from IE.
Maybe there is someting wrong in my client so that I can't get WGA Tools.
Thank you for your answering!

**Comment by ExplodingBottle** [comment]
Thank you too for your interest in this project, which is not really known.
